### ISSUE TITLE
Add ABI tracker for opencc

### ISSUE THREAD

**Issue by yan12125** [lvc/abi-tracker#10]
Hi, could you add the ABI tracker for opencc, a Traditional/Simplified Chinese conversion library?

Project homepage: https://github.com/BYVoid/OpenCC

**Comment by lvc** [comment]
Hi,

The library has been added at https://abi-laboratory.pro/?view=timeline&l=opencc

Feel free to add more libraries to the tracker.

![opencc-1](https://user-images.githubusercontent.com/1517837/46586278-e61db300-ca84-11e8-98e3-cfe54990ee72.png)
