### ISSUE TITLE
Adding UCX

### ISSUE THREAD

**Issue by jakirkham** [lvc/abi-tracker#12]
It would be helpful to have the [UCX]( https://github.com/openucx/ucx ) communication library added to the tracker.

**Comment by linuxhw** [comment]
Done: https://abi-laboratory.pro/?view=timeline&l=ucx

![UCX](https://user-images.githubusercontent.com/15686469/72964267-77c04980-3dca-11ea-9916-25966f757c6e.png)

**Comment by jakirkham** [comment]
Thanks @linuxhw! 😄
