### ISSUE TITLE
Missing recent OpenEXR versions

### ISSUE THREAD

**Issue by jakirkham** [lvc/abi-tracker#13]
It looks like the last release of OpenEXR on ABI laboratory is 2.3.0. Though there have been a few 2.4 and 2.5 releases since. Would be great to include them in the tracker 🙂

**Comment by bsdhw** [comment]
This was obsolete link to download new tarballs. This is fixed now.

See updated report https://abi-laboratory.pro/index.php?view=timeline&l=openexr

Thanks.

**Comment by jakirkham** [comment]
Thanks :)
