### ISSUE TITLE
Updating UCX

### ISSUE THREAD

**Issue by jakirkham** [lvc/abi-tracker#15]
The latest release on the ABI Tracker is 1.8.1 whereas UCX is on 1.12.0 with 1.12.1 in RC currently. Would be good to update this

**Comment by linuxhw** [comment]
Done: https://abi-laboratory.pro/index.php?view=timeline&l=ucx

![Screenshot-20220401191844-676x565](https://user-images.githubusercontent.com/15686469/161303036-089b592b-6dbd-40d5-9085-f0106383f68c.png)

**Comment by jakirkham** [comment]
This is great! 😄 Thank you 🙏
