### ISSUE TITLE
Could libgeotiff please be updated?

### ISSUE THREAD

**Issue by akrherz** [lvc/abi-tracker#16]
https://abi-laboratory.pro/index.php?view=timeline&l=libgeotiff has 1.6.0, whereas 1.7.1 is the latest.  Thanks!

**Comment by linuxhw** [comment]
The report has been updated: https://abi-laboratory.pro/?view=timeline&l=libgeotiff

![Screenshot-20220331191227-714x480](https://user-images.githubusercontent.com/15686469/161101395-1da2d412-72f6-476d-9e61-52aeb316031b.png)
