### ISSUE TITLE
abi-viewer

### ISSUE THREAD

**Issue by cinemast** [lvc/abi-tracker#4]
Hi!

I have a question about abi-viewer. Which tool is that and where can it be obtained?

**Comment by lvc** [comment]
Hi,

This is the next generation tool for high-detailed **visual** analysis of ABI changes in a C or C++ library.

Unlike the abi-compliance-checker this tool allows you to view the structure and alignment of data types, calling stacks, virtual tables, etc. See example for libssh 0.5.5 vs 0.6.0: http://abi-laboratory.pro/preview/abi-report/libssh-0.5.5vs0.6.0/symbols.html

This is the only one closed source tool among others in the project. One can only purchase reports of the tool. See details here:

http://abi-laboratory.pro/abi-report.html
http://abi-laboratory.pro/abi-view.html

Thank you.

**Comment by cinemast** [comment]
Ah ok. Thanks for the clarification. 

One additional question, ist it possible to somehow turn changelog and pkgdiff generation on for all versions of a library, without having to replace each occurence in the .json file?

**Comment by lvc** [comment]
Hello,

You can set two properties outside the versions descriptors (near the "Name" and "SourceUrl" properties in the *.json file) to enable changelog and pkgdiff generation for new versions:

    "PkgDiff": "On",
    "Changelog": "On",

I'll describe all properties in the docs soon ...

Thank you.

**Comment by cinemast** [comment]
Ah, I will try that. Thank you.
