### ISSUE TITLE
ABI tracker inconsistently picked up compile option

### ISSUE THREAD

**Issue by paroj** [lvc/abi-tracker#7]
A new compile option OGRE_USE_STD11 was recently introduced to Ogre, which defaults to FALSE in CMake.
[However the abi tracker seems to assume it to be set](https://abi-laboratory.pro/tracker/compat_report/ogre/1.10.7/current/34d52/src_compat_report.html#Removed) - using std::shared_ptr instead of [Ogre::SharedPtr](https://github.com/OGRECave/ogre/blob/master/OgreMain/include/OgreSharedPtr.h#L41)

[On the other hand it sees Ogre::AtomicScalar instead of std::atomic here](https://github.com/OGRECave/ogre/blob/master/OgreMain/include/OgreAtomicScalar.h#L35).

It seems like the [build settings](https://github.com/OGRECave/ogre/blob/master/CMake/Templates/OgreBuildSettings.h.in) are not parsed correctly/ consistently.

**Comment by lvc** [comment]
Hi Pavel,

Report has been fixed: https://abi-laboratory.pro/tracker/timeline/ogre/

The library is compiled with default OGRE_USE_STD11=FALSE. The issue has been caused by mulfunction of the abi-dumper tool.

Thank you.

**Comment by paroj** [comment]
thanks :+1:
