### ISSUE TITLE
ABI tracking for openfst

### ISSUE THREAD

**Issue by 183amir** [lvc/abi-tracker#8]
Could you please add openfst as well to the your ABI tracking website, please?
Available here: http://www.openfst.org

**Comment by lvc** [comment]
The report is now available at https://abi-laboratory.pro/tracker/timeline/openfst/.

![openfst-2](https://user-images.githubusercontent.com/1517837/34942681-981d9e5a-fa09-11e7-9c89-2ff0c9b2dfed.png)
![openfst-1](https://user-images.githubusercontent.com/1517837/34942682-9841f0a2-fa09-11e7-9b20-9ab300a08f3f.png)

**Comment by 183amir** [comment]
Thank you!
